name: Precio diario

on:
  schedule:
    - cron: '22 30 * * *' # Runs every day at 22:30 UTC que son las 6pm hora venezuela, ya el banco debe haber publicado los precios
  workflow_dispatch:  # Allows manual triggering

jobs:
  extrayendo_dato:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Descargar precios USD y EUR
        run: |
          chmod +x get_prices.sh
          bash get_prices.sh
          if [ ! -s prices.csv ]; then
            echo "CSV file is empty"
            exit 1
          fi

      - name: Commit results
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || git stash
          git pull --rebase origin main
          git stash list | grep "stash@{0}" && git stash apply
          git add prices.csv
          git diff --cached --exit-code || git commit -m "Precios actualizados" --allow-empty
          git push --force-with-lease origin HEAD:main